=== BruceZu/BadAssWebApp/src/test/resources/Persons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">
	<xsd:annotation>
		<xsd:appinfo>
			<jaxb:schemaBindings>
				<jaxb:package name="org.elite.java.jaxb"/>
			</jaxb:schemaBindings>
		</xsd:appinfo>
	</xsd:annotation>
	<xsd:element name="Persons">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Person" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Name" type="xsd:string"/>
							<xsd:element name="Height" type="xsd:short"/>
							<xsd:element name="Weight" type="xsd:short"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== BruceZu/BadAssWebApp/src/test/resources/Persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:noNamespaceSchemaLocation="Persons.xsd">
	<Person>
		<Name>Andreas</Name>
		<Height>190</Height>
		<Weight>80</Weight>
	</Person>
	<Person>
		<Name>Idar</Name>
		<Height>180</Height>
		<Weight>90</Weight>
	</Person>
	<Person>
		<Name>Torben</Name>
		<Height>194</Height>
		<Weight>108</Weight>
	</Person>
</Persons>
